spring.application.name=filebonsai-catalog
server.address=127.0.0.1
springdoc.api-docs.version=OPENAPI_3_0
springdoc.writer-with-order-by-keys=true
springdoc.override-with-generic-response=false
spring.jackson.deserialization.fail-on-unknown-properties=true
spring.jackson.deserialization.fail-on-trailing-tokens=true
spring.jackson.mapper.allow-coercion-of-scalars=false
spring.jackson.serialization.write-dates-as-timestamps=false
