spring.flyway.enabled=true
spring.jooq.sql-dialect=POSTGRES
spring.autoconfigure.exclude=
filebonsai.access.cookie.secure=true
filebonsai.storage.local.root=${FILEBONSAI_STORAGE_ROOT:./data}
filebonsai.transfers.maximum-bytes=${FILEBONSAI_MAXIMUM_UPLOAD_BYTES:134217728}
filebonsai.transfers.maximum-duration=${FILEBONSAI_MAXIMUM_UPLOAD_DURATION:15m}
filebonsai.transfers.maximum-concurrent-writes=${FILEBONSAI_MAXIMUM_CONCURRENT_WRITES:4}
filebonsai.transfers.expiry=${FILEBONSAI_UPLOAD_EXPIRY:24h}
